### PR TITLE
Added the tmp.install.packages() function

### PR DESCRIPTION
**Pull request by juba**
Hi,

And first, thanks for the initiative of creating this package ! It should be very handy to have all these functions in one place.

This pull request is just to add the tmp.install.packages() function, as mentioned in Issue #1. Feel free to accept, correct or reject it.

Thanks !

Julien

### CODE REVIEW

**Comment by sebastian-c** [comment]
Given that a tempdir is constant within a session, maybe there should be a line `if tempdir() %in% .libPaths`. If so, install into that directory. If not, add tempdir to .libPaths.

**Comment by mrdwab** [comment]
@juba I vote for accept it, of course! Can you link to the Q&A on SO? Wasn't there some discussion at the question? @sebastian-c Didn't realize that `tempdir()` was constant per session, but your suggestion sounds good too.

**Comment by juba** [comment]
Totally agree with your suggestions, and just tried to add them to my pull request.

**Comment by sebastian-c** [comment]
One question about this function, though. Say I run it and then I want to go back to my regular library. Should we have another function which undoes the temp library or just a parameter to this one?

**Comment by juba** [comment]
What do you mean exactly by "go back to my regular library" ? I think that either restarting your R session, or just unload the package should be enough ?

**Comment by sebastian-c** [comment]
My apologies, your function deals with the issue by ensuring that the temporary library is never first in the libPath.

**Comment by juba** [comment]
No problem. I'm glad there's nothing specific to do :-)

**Pull request closed without merging**
